on: [push]
jobs:
  build:
    container:
      image: docker:28.0.1-dind-alpine3.21
    steps:
      - run: apk add --update nodejs
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: lautis-dresden/anfragensystem:latest