import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Technik anfragen | Lautis Dresden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body
        className={`${inter.className} antialiased w-full min-h-screen bg-[url('/background.jpg')] bg-cover bg-center bg-fixed dark`}
      >
        <div className="w-full min-h-screen bg-slate-950 bg-opacity-60">
          {children}
        </div>
      </body>
    </html>
  );
}
