import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Technik anfragen | Lautis Dresden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" suppressHydrationWarning>
      <head />

      <body>
        <div
          className={`${inter.className} antialiased w-full min-h-screen bg-[url('/background.jpeg')] bg-cover bg-center bg-fixed dark`}
        >
          <ThemeProvider attribute="class" forcedTheme="dark" enableSystem>
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
